apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hhpd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hhpd
    app.kubernetes.io/part-of: byoc-app-zmze
  name: hhpd
spec:
  rules:
  - host: hhpd-byoc-jsqn-tenant.apps.b4fcf6f6dab0aa2d281c.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: hhpd
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
