apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hhpd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hhpd
    app.kubernetes.io/part-of: byoc-app-zmze
  name: hhpd
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: hhpd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: hhpd
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-jsqn-tenant/byoc-app-zmze/hhpd@sha256:42c540a5eae45665b69022c35538df4e5bddf1082337dd76ed2375f9ec758173
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
